// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcwu2kN6FaxaNW61IqZY7ayPzAZ1rT6wk',
    appId: '1:325738421283:web:c7ceec2812d984a7706596',
    messagingSenderId: '325738421283',
    projectId: 'informatorems-784a1',
    authDomain: 'informatorems-784a1.firebaseapp.com',
    storageBucket: 'informatorems-784a1.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcwu2kN6FaxaNW61IqZY7ayPzAZ1rT6wk',
    appId: '1:325738421283:web:c7ceec2812d984a7706596',
    messagingSenderId: '325738421283',
    projectId: 'informatorems-784a1',
    authDomain: 'informatorems-784a1.firebaseapp.com',
    storageBucket: 'informatorems-784a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwvRJr4rDRrfBru-G2YsuF-Uq2ZI5NXuw',
    appId: '1:325738421283:android:ad06bd23e8014c9a706596',
    messagingSenderId: '325738421283',
    projectId: 'informatorems-784a1',
    storageBucket: 'informatorems-784a1.firebasestorage.app',
  );
}
